FROM --platform=amd64 ubuntu:20.04 

ENV TZ=America/Toronto  
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    tzdata \
    software-properties-common \
    python3 \
    python3-pip \
    gcc \
    gfortran \
    musl-dev
    
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y \
    python3.7-venv \
    python3.7-dev \
    python3.7-tk

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
RUN update-alternatives --config python3
    
RUN /usr/bin/python3.7 -m pip install --upgrade pip
COPY requirements.txt /tmp/pip-tmp/
RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
   && rm -rf /tmp/pip-tmp
RUN pip3 install --upgrade quadprog

CMD ["python3"]